# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Software Design and Analysis Lab
tagline: We are the Software Design and Analysis Lab at Carnegie Mellon University!
email: parvk@cs.cmu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Researching and developing tools for Software Assurance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cmu-soda.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  parvkpr
lang: en
last_updated: true
# Build settings
# theme: minima
# permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-scholar
  - kramdown-parser-gfm
  # - github-pages
  
theme: bulma-clean-theme
# remote_theme: chrisrhymes/bulma-clean-theme
# baseurl: "/my-project"
# plugins:
# - github-pages
# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
collections:
  team:
    output: true
    layout: page
    show_sidebar: false
  news:
    # defaults:
    #   layout: post
    output: true
    #permalink: /news/:path/
  # projects:
  #   output: true
  #   #permalink: /projects/:path/
  tools:
    output: true
  #   #permalink: /tools/:path/
  projects: 
    output: true
    layout: product
    show_sidebar: false
  reu:
    output: true
    layout: product
    show_sidebar: false
    permalink: /reu/:name/
navbar_fixed: true
footer_fixed: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Parv Kapoor"
      layout: post
      hero_image: /path/to/hero-image.jpg
      show_sidebar: true
scholar:
  style: simple-ieee.csl
  bibliography_list_tag: "ol"
  bibliography_template: bibtemplate
# scholar:
#   style: apa
#   source: ./bibliography
#   bibliography: references.bib
#   bibliography_template: bib
#   query: "@*"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
