// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function add(a, b) {
  return a + b | 0;
}

function Counter(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement("h3", undefined, String(match[0])), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (prev) {
                                    return prev + 1 | 0;
                                  }));
                    })
                }, "Increment"));
}

var make = Counter;

exports.add = add;
exports.make = make;
/* react Not a pure module */
