// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Counter = require("./components/Counter.bs.js");

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hello World "), React.createElement(Counter.make, {}));
}

var make = App;

exports.make = make;
/* react Not a pure module */
